[package]
name = "probe-rs-debug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { path = "../probe-rs" }
simplelog = "^0.12.0"
log = "0.4"
anyhow = "1.0"
object = "0.29"
